src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $price = null;

    // #[ORM\Column(length: 255)]
    // private ?string $picture = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Status $fk_status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture_url = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    /**
     * @ORM\OneToMany(mappedBy="product", targetEntity=ProductInCart::class, orphanRemoval=true)
     * @ORM\JoinColumn(name="id", referencedColumnName="fk_product_id")
     */
    private Collection $ProductInCart;


    public function __construct()
    {
        $this->ProductInCart = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    // public function getPicture(): ?string
    // {
    //     return $this->picture;
    // }

    // public function setPicture(string $picture): static
    // {
    //     $this->picture = $picture;

    //     return $this;
    // }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getFkStatus(): ?Status
    {
        return $this->fk_status;
    }

    public function setFkStatus(?Status $fk_status): static
    {
        $this->fk_status = $fk_status;

        return $this;
    }

    public function getPictureUrl(): ?string
    {
        return $this->picture_url;
    }

    public function setPictureUrl(?string $picture_url): static
    {
        $this->picture_url = $picture_url;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @return Collection<int, ProductInCart>
     */
    public function getProductInCart(): Collection
    {
        return $this->ProductInCart;
    }

    public function addProductInCart(ProductInCart $productInCart): static
    {
        if (!$this->ProductInCart->contains($productInCart)) {
            $this->ProductInCart->add($productInCart);
            $productInCart->setProduct($this);
        }

        return $this;
    }

    public function removeProductInCart(ProductInCart $productInCart): static
    {
        if ($this->ProductInCart->removeElement($productInCart)) {
            // set the owning side to null (unless already changed)
            if ($productInCart->getProduct() === $this) {
                $productInCart->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/UserAccessController.php
<?php

namespace App\Controller;

use App\Service\FileUploader;
use Doctrine\Persistence\ManagerRegistry;
use App\Form\UserProfileType;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserAccessController extends AbstractController
{
    #[Route('/', name: 'app_user_access')]
    public function index(ProductRepository $productRepo, EntityManagerInterface $entityManager): Response
    {
        // $user = $this->getUser();
        $categories = $entityManager->getRepository(Product::class)->createQueryBuilder('p')
            ->select('DISTINCT p.categorie')
            ->getQuery()
            ->getResult();
        return $this->render('user_access/index.html.twig', [
            'products' => $productRepo->findAll(),
            'categories' => $categories,
        ]);
    }

    #[Route('user/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(Product $product): Response
    {

        $user = $this->getUser();
        return $this->render('show.html.twig', [
            'product' => $product,
            'user' => $user,

        ]);
    }


    // #[Route('/profile', name: 'app_user_profile', methods: ['GET'])]
    // public function profile(Product $product): Response
    // {
    //     $user = $this->getUser();

    //     return $this->render('profile/profile.html.twig', [
    //         'product' => $product,
    //         'user' => $user,
    //     ]);
    // }

    /**
     * @Route("/edit-profile", name="edit_profile")
     */

    #[Route('/profile', name: 'profile', methods: ['GET', 'POST'])]
    // ...
    public function profile(Request $request, ManagerRegistry $doctrine, EntityManagerInterface $entityManager, FileUploader $fileUploader): Response
    {
        $entityManager = $doctrine->getManager();
        $user = $this->getUser();
        $form = $this->createForm(UserProfileType::class, $user);
        $form->handleRequest($request);
        $roles = $this->getUser()->getRoles();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();


            if (in_array('ROLE_ADMIN', $roles)) {
                return $this->redirectToRoute('admin'); // Redirect admin to /products
            } elseif (in_array('ROLE_USER', $roles)) {
                return $this->redirectToRoute('app_user_access'); // Redirect user to /user
            }
        }

        return $this->render('profile/profile.html.twig', [
            'editForm' => $form->createView(),
            'form' => $form,
        ]);
    }
    // ...

}

templates/user_access/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marketplace{% endblock %}

{% block body %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap');
/* Style the "Show" button */
.btn-outline-primary {
  background-color: transparent;
  border-color: #007bff;
  color: #007bff;
  border-radius: 20px;
  padding: 7px 20px;
  font-weight: bold;
  transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out;
  /* text-transform: uppercase; */
}

.btn-outline-primary:hover {
  background-color: #007bff;
  color: #fff;
}

/* Style the "Add to Cart" button */
.btn-outline-warning {
  background-color: transparent;
  border-color: #ffc107;
  color: #ffc107;
  border-radius: 20px;
  padding: 10px 20px;
  font-weight: bold;
  transition: background-color 0.3s ease-in-out, color 0.3s ease-in-out;
  /* text-transform: uppercase; */
}

.btn-outline-warning:hover {
  background-color: #ffc107;
  color: #000;
}

/* Style the cart icon within the "Add to Cart" button */
.btn-outline-warning i {
  margin-right: 5px;
  font-size: 1.2em;
}

/* Adjust button margins */
.my-1 {
  margin-top: 10px;
}


.btn-group-2 {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.textcardpic{
  text-shadow: 1px 1px 2px black;
}
/* Add more styles as needed */

.featProducts{
  font-weight: 400;
  /* font-family: 'Quicksand', sans-serif; */
}
.secondbarU{
        height: 5px;
        /* background-color: rgb(210, 29, 29); */
        background-image: linear-gradient(rgba(98, 98, 98, 0.126), rgba(228, 228, 228, 0));
    }
</style>

<main>
  

  
  {% include '_slider_home.html.twig' %}
 
   <hr>
  </div>
  {# <div class="position-relative overflow-hidden    text-center  bgImage">
    <div class="col-md-6  mx-auto my-5">
      <h1 class="display-3 fw-bold ober2">Designed for engineers</h1>
      <h3 class="fw-normal  text-white-75 mb-3 ober1">Build anything you want with Symfony</h3>
      <div class="d-flex gap-3 justify-content-center lead fw-normal">
       
      </div>
    </div>
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div> #}

  {% include '_sidebar.html.twig' %}

   
    <div class="container my-1">
      <div class="conti d-flex">
      <button class="viewProd btn btn-outline-secondary me-3"><i class="bi bi-view-list"></i></button>
      <h3 class="text-center featProducts">Featured Products</h3>
      </div>
      
      <div class="album py-2">
        <div class="container">

          
        
 <script>
  $(document).ready(function() {
    $(".viewProd").click(function() {
      var currentClass = $(".viewPort").attr("class");
      var newClass = "";

      if (currentClass.includes("row-cols-lg-3")) {
        newClass = currentClass.replace("row-cols-lg-3", "row-cols-lg-4");
      } else if (currentClass.includes("row-cols-lg-4")) {
        newClass = currentClass.replace("row-cols-lg-4", "row-cols-lg-5");
      } else if (currentClass.includes("row-cols-lg-5")) {
        newClass = currentClass.replace("row-cols-lg-5", "row-cols-lg-3");
      } else {
        newClass = currentClass + " row-cols-lg-3";
      }

      $(".viewPort").attr("class", newClass);
    });
  });
</script>


          <div class="row row-cols-1 row-cols-sm-1  row-cols-md-2 row-cols-lg-3 g-3 viewPort">
            {% for product in products %}
            <div class="col">
              <div class="card shadow-sm border border-0 h-100">

                <a href="{{ path('app_product_show', {'id': product.id}) }}"><img
                    src="{{ asset('pictures/' ~ product.imageName) }}" class="w-75 mt-2 mx-auto d-block rounded" alt="..."></a>
                
                    <div class="card-body text-center">

                  <p class="card-text">Name: <b>{{ product.name }}</b></p>


                  <p class="card-text"> Description: <b>{{ product.description }} </b></p>


                  {# <p class="card-text"> ID: <b>{{ product.id }} </b></p> #}

                  {# <p class="card-text"> Date: <b>{{ product.date ? product.date|date('Y-m-d ') : ''
                      }}</b></p> #}

                  <p class="card-text"> Categorie: <b>{{ product.categorie }}</b></p>


                 

                  {# <p class="card-text">Status:
                    <b class="{% if product.fkStatus.status == 'Open' %}
                                status-open{% elseif product.fkStatus.status == 'Done' %}
                                status-done{% elseif product.fkStatus.status == 'Pending' %}
                                status-reserved{% elseif product.fkStatus.status == 'Reserved' %}
                                status-sold{% elseif product.fkStatus.status == 'Sold' %}
                                status-pending{% else %}
                                status-default{% endif %}">
                      {{ product.fkStatus.status }}</b>
                  </p> #}

<div class="btn-group-2 d-grid gap-2 w-50 d-block mx-auto">
  <a href="{{ path('app_product_show', {'id': product.id}) }}"
      class="btn btn-outline-primary text-center">Show</a>
  <form action="{{ path('app_add_to_cart', {'productid': product.id, 'quantity': 1, 'userid': app.user.id}) }}"
      method="post">
      <button type="submit" class="btn btn-outline-warning text-black my-1 text-center">
          <i class="bi bi-cart3 h6"></i> Add to Cart
      </button>
  </form> <p class="card-text">Price: <b>{{ product.price }} $</b></p>
</div>

                </div>
              </div>
            </div>

            {% else %}

            <p colspan="8">no records found</p>

            {% endfor %}



          </div>
          {#
          <hr> #}
  </main>
  </div>
  </div>
  </div>
  


  {% endblock %}